label.titulo.pagina = TITULO DA PAGINA
label.selecione=Selecione...
label.limpar=Limpar
label.salvar=Salvar
label.funcionarios=Funcion\u00E1rios
label.agenda=Agenda
label.agendas=Agendas
label.compromisso=Compromisso
label.compromissos=Compromissos
label.data=Data
label.hora=Hora
label.nao.atribuido=N\u00E3o Atribu\u00EDdo
label.sistema.nome=Sistema SOC
label.menu.relatorio=Gerar Relat\u00F3rio
label.codigo=C\u00F3digo
label.limpar.formulario=Limpar Formul\u00E1rio
label.atencao=ATEN\u00C7\u00C3O
label.funcionario=Funcion\u00E1rio
label.abrir=ABRIR
label.periodo=Per\u00EDodo
label.novo = NOVO
label.agenda.nova=Nova Agenda
label.agenda.editar=Editar Agenda
label.agenda.detalhes=Detalhes da Agenda
label.agenda.novo.compromisso=Agendar novo compromisso nessa agenda\:
label.agenda.sem.compromisso=Nenhum compromisso marcado nesta agenda.
label.agenda.voltar=Voltar para Agendas
label.compromisso.novo=Novo Compromisso
label.compromisso.editar=Editar Compromisso
label.compromisso.nome=Nome do Compromisso
label.compromisso.funcionario.responsavel=Funcion\u00E1rio Respons\u00E1vel
label.compromisso.agendar=Agendar
label.compromisso.placeholder=Ex\: Consulta M\u00E9dica
label.agenda.cadastradas=Agendas Cadastradas
label.compromisso.cadastrados=Compromissos Cadastrados
label.relatorio.gerar=Gerar Relat\u00F3rio
label.relatorio.impressao=Impress\u00E3o - Relat\u00F3rio
label.relatorio.titulo=Relat\u00F3rio
label.relatorio.data.inicial=Data Inicial
label.relatorio.data.final=Data Final
label.relatorio.gerar.html=Gerar em Tela (HTML)
label.relatorio.gerar.xls=Baixar Planilha (XLS)
label.relatorio.voltar=Voltar para Filtros
label.relatorio.codigo.funcionario=C\u00F3digo do Funcion\u00E1rio
label.relatorio.nome.funcionario=Nome do Funcion\u00E1rio
label.relatorio.codigo.agenda=C\u00F3digo da Agenda
label.relatorio.nome.agenda=Nome da Agenda
label.relatorio.sem.resultado=Nenhum resultado encontrado para o per\u00EDodo selecionado.
label.excluir = EXCLUIR
label.editar = EDITAR
label.acao = A\u00C7\u00C3O
label.id = ID
label.nome = Nome
label.funcionario.novo=Novo Funcion\u00E1rio
label.funcionario.editar=Editar Funcion\u00E1rio
label.buscar.por = BUSCAR POR
label.escolha = ESCOLHA...
label.pesquisar = PESQUISAR
label.sim = SIM
label.nao = NAO
label.modal.titulo = CONFIRMA\u00C7\u00C3O DE EXCLUS\u00C3O
label.modal.corpo = DESEJA EXCLUIR ?
